# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lsilva-x <lsilva-x@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/01 00:18:45 by lsilva-x          #+#    #+#              #
#    Updated: 2024/09/01 03:30:06 by lsilva-x         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

FLAGS = -Wall -Wextra -Werror

OBJS = ${SRCS: .c=.o}

SRCS = src/main.c


all: ${NAME}

${NAME}: ${OBJS}
	cc {SRCS} ${FLAGS} -o {NAME}

clean:
	rm -r ${OBJS}

fclean: clean
	rm -f ${NAME}
	

